title: cogniviDAR
description: Plataforma digital que une educación y bienestar para transformar vidas.
baseurl: ""
url: "https://congnividar.com"
theme: null
markdown: kramdown
exclude: ["README.md"]
